### ISSUE TITLE
点击注册按钮没有反应

### ISSUE THREAD

**Issue by yuanzilin** [AHRL/myChat#3]
我能用npm run dev成功把项目跑起来，但是没办法注册账号。是不是因为我没运行npm run server，或者缺少后端的代码？

**Comment by yuanzilin** [comment]
没办法注册账号的具体表现是，点击注册按钮没反应,并且报错如下：
![image](https://user-images.githubusercontent.com/39659228/79760036-0a34a280-8352-11ea-9c36-4c7a2ab88d5f.png)

**Comment by AHRL** [comment]
另开一个终端执行npm run server就可以了
